teastore_auth:
  replicas: 2
  resources:
    memory: "256M"
    cpu: "100m"
  service:
    type: ClusterIP # ClusterIP, NodePort, LoadBalancer
    targetPort: 8080
    port: 8080 ## External Port for LoadBalancer/NodePort

teastore_db:
  replicas: 1
  resources:
    memory: "256M"
    cpu: "100m"
  service:
    type: ClusterIP # ClusterIP, NodePort, LoadBalancer
    targetPort: 3306
    port: 3306 ## External Port for LoadBalancer/NodePort

teastore_image:
  replicas: 2
  resources:
    memory: "256M"
    cpu: "100m"
  service:
    type: ClusterIP # ClusterIP, NodePort, LoadBalancer
    targetPort: 8080
    port: 8080 ## External Port for LoadBalancer/NodePort

teastore_loadgen:
  replicas: 1
  resources:
    memory: "256M"
    cpu: "100m"
  settings:
    num_users: 10
    ramp_up: 1

teastore_loadgen_amex:
  replicas: 1
  resources:
    memory: "256M"
    cpu: "100m"
  settings:
    num_users: 10
    ramp_up: 1

teastore_persistence:
  replicas: 2
  resources:
    memory: "256M"
    cpu: "100m"
  service:
    type: ClusterIP # ClusterIP, NodePort, LoadBalancer
    targetPort: 8080
    port: 8080 ## External Port for LoadBalancer/NodePort

teastore_recommender:
  replicas: 2
  resources:
    memory: "256M"
    cpu: "100m"
  service:
    type: ClusterIP # ClusterIP, NodePort, LoadBalancer
    targetPort: 8080
    port: 8080 ## External Port for LoadBalancer/NodePort

teastore_registry:
  replicas: 2
  resources:
    memory: "256M"
    cpu: "100m"
  service:
    type: ClusterIP # ClusterIP, NodePort, LoadBalancer
    targetPort: 8080
    port: 8080 ## External Port for LoadBalancer/NodePort

teastore_webui:
  replicas: 2
  resources:
    memory: "256M"
    cpu: "100m"
  service:
    type: LoadBalancer # ClusterIP, NodePort, LoadBalancer
    targetPort: 8080
    port: 8080 ## External Port for LoadBalancer/NodePort
  env:
    visa_url: "https://fso-payment-gw-sim.azurewebsites.net/api/payment"
    mastercard_url: "https://fso-payment-gw-sim.azurewebsites.net/api/payment"
    amex_url: "https://amex-fso-payment-gw-sim.azurewebsites.net/api/payment"
