apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-registry
  labels:
    framework: java
    app: registry
    tier: registry
    app.kubernetes.io/part-of: teastore
    app.kubernetes.io/component: registry
spec:
  replicas: {{ .Values.teastore_registry.replicas }}
  selector:
    matchLabels:
      app: registry
      tier: registry
  template:
    metadata:
      labels:
        app: registry
        tier: registry
        version: v1
    spec:
      containers:
        - name: teastore-registry
          # image: brownkw/teastore-registry
          image: public.ecr.aws/d8i9k4x3/fso-lab-teastore-registry
          resources:
            requests:
              memory: {{ .Values.teastore_registry.resources.memory }}
              cpu: {{ .Values.teastore_registry.resources.cpu }}
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-registry
  labels:
    app: registry
    tier: registry
spec:
  type: {{ .Values.teastore_registry.service.type }}
  ports:
    - port: {{ .Values.teastore_registry.service.port }}
      protocol: TCP
      targetPort: {{ .Values.teastore_registry.service.targetPort }}
  selector:
    tier: registry
