apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-loadgen
  labels:
    app: loadgen
    tier: loadgen
    app.kubernetes.io/part-of: teastore
    app.kubernetes.io/component: loadgen
spec:
  selector:
    matchLabels:
      app: loadgen
      tier: loadgen
  template:
    metadata:
      labels:
        app: loadgen
        tier: loadgen
        version: v1
    spec:
      containers:
        - name: teastore-loadgen
          # image: brownkw/teastore-loadgen
          image: public.ecr.aws/d8i9k4x3/fso-lab-teastore-loadgen
          resources:
            requests:
              memory: {{ .Values.teastore_loadgen.resources.memory }}
              cpu: {{ .Values.teastore_loadgen.resources.cpu }}
          ports:
            - containerPort: 8080
          args: [ "-t", "/teastore_browse_nogui.jmx", "-Jhostname", "teastore-webui", "-Jport", "{{ .Values.teastore_webui.service.port }}", "-JnumUser", "{{ .Values.teastore_loadgen.settings.num_users }}", "-JrampUp", "{{ .Values.teastore_loadgen.settings.ramp_up }}", "-n"]
