apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-auth
  labels:
    framework: java
spec:
  replicas: {{ .Values.teastore_auth.replicas }}
  selector:
    matchLabels:
      app: teastore
      run: teastore-auth
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-auth
    spec:
      containers:
        - name: teastore-auth
          image: brownkw/teastore-auth
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: {{ .Values.teastore_auth.resources.memory }}
              cpu: {{ .Values.teastore_auth.resources.cpu }}
          env:
            - name: HOST_NAME
              value: "teastore-auth"
            - name: REGISTRY_HOST
              value: "teastore-registry"
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-auth
  labels:
    app: teastore
    run: teastore-auth
spec:
  type: {{ .Values.teastore_auth.service.type }}
  ports:
    - port: {{ .Values.teastore_auth.service.port }}
      protocol: TCP
      targetPort: {{ .Values.teastore_auth.service.targetPort }}
  selector:
    run: teastore-auth
