apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-recommender
  labels:
    framework: java
spec:
  replicas: {{ .Values.teastore_recommender.replicas }}
  selector:
    matchLabels:
      app: teastore
      run: teastore-recommender
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-recommender
    spec:
      containers:
        - name: teastore-recommender
          image: brownkw/teastore-recommender
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: {{ .Values.teastore_recommender.resources.memory }}
              cpu: {{ .Values.teastore_recommender.resources.cpu }}
          env:
            - name: HOST_NAME
              value: "teastore-recommender"
            - name: REGISTRY_HOST
              value: "teastore-registry"
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-recommender
  labels:
    app: teastore
    run: teastore-recommender
spec:
  type: {{ .Values.teastore_recommender.service.type }}
  ports:
    - port: {{ .Values.teastore_recommender.service.port }}
      protocol: TCP
      targetPort: {{ .Values.teastore_recommender.service.targetPort }}
  selector:
    run: teastore-recommender
