apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-auth
  labels:
    framework: java
    app: auth
    tier: auth
    app.kubernetes.io/part-of: teastore
    app.kubernetes.io/component: auth
spec:
  replicas: {{ .Values.teastore_auth.replicas }}
  selector:
    matchLabels:
      app: auth
      tier: auth
  template:
    metadata:
      labels:
        app: auth
        tier: auth
        version: v1
    spec:
      containers:
        - name: teastore-auth
          image: brownkw/teastore-auth
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: {{ .Values.teastore_auth.resources.memory }}
              cpu: {{ .Values.teastore_auth.resources.cpu }}
          env:
            - name: HOST_NAME
              value: "teastore-auth"
            - name: REGISTRY_HOST
              value: "teastore-registry"
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-auth
  labels:
    app: auth
    tier: auth
spec:
  type: {{ .Values.teastore_auth.service.type }}
  ports:
    - port: {{ .Values.teastore_auth.service.port }}
      protocol: TCP
      targetPort: {{ .Values.teastore_auth.service.targetPort }}
  selector:
    tier: auth
